### ISSUE TITLE
lftp: command not found

### ISSUE THREAD

**Issue by B-Stewart** [welaika/docker-wordmove#14]
When trying to run a command like `wordmove pull -e production --all`
The file downloads will fail with 
`lftp: command not found`

This is because it isn't installed anywhere in the docker file / parent image. IMO this docker file should install lftp as it does other dependencies if the wordmove is going to rely on it.

**Comment by alessandro-fazzi** [comment]
Hello @B-Stewart ,

you are right and I think we should have it inside the images, even if FTP is a hard weight (hard to be supported/maintained in Wordmove and someway obsolete). Since Wordmove supports it, it have to be there with no doubts.

I'll work on the update but I have not a window before the half of the month.

Thank you very much

**Comment by alessandro-fazzi** [comment]
Half of February passed; but I'm on it now. Better later than ever?

Aside the main topic: it's important to point out the tag you're using. This is not the case, but a bug could be tag-related in many scenarios ;)

**Comment by alessandro-fazzi** [comment]
@B-Stewart the updated images are being crunched by DockerHub at the moment. I've already tested them locally and the `lftp` command in now there :)

I've also updated the readme both here and on DockerHub with the new bits.

Just be patient for 15 minutes and updated images (both `php7` and `alpine`) will be public.

Going to close this bug.

Thank you very much for your contribution 😃
