### ISSUE TITLE
Alpine version

### ISSUE THREAD

**Issue by alessandro-fazzi** [welaika/docker-wordmove#3]
I've previously shared with @simonbland the snippet for an Alpine version.

I'd like to publish it as `welaika/wordmove:alpine` docker image. And then find someone who'd like to test it ;)

**Comment by alessandro-fazzi** [comment]
REF https://cl.ly/2G071f430K0B

**Comment by maiorano84** [comment]
This looks very close to what I came up with on my own in my [now-closed issue](https://github.com/welaika/docker-wordmove/issues/6) before coming across this one. My only suggestion would be to create a separate user with the following directives:

    RUN adduser -S wordmove
    USER wordmove

This will avoid the "permissions too open" error if users decide to mount their .ssh directory with any existing keys they might want to use ( `/home/wordmove/.ssh` ) for ssh-based deployments.

Since a user directory will be created under `/home`, it might be best to use a different working directory for project files. `/var/www/html` is common, but might be too verbose when specifying a mount point. `WORKDIR /html` is probably enough.

**Comment by alessandro-fazzi** [comment]
I'm really glad to have all these suggestions. I'm reading and taking in consideration all of them.

One quick question: in `RUN adduser -S wordmove` I can't find documentation about the `-S` flag; can you help me?

**Comment by maiorano84** [comment]
@pioneerskies 
Sure thing:

The -S flag in Alpine Linux is equivalent to Ubuntu's -r flag; they both add the user to the system group. Not sure if it's completely necessary, so you *might* be safe in taking it out.

**Comment by alessandro-fazzi** [comment]
Ah ok...damn...I was a Linux sysadmin once upon a time. Now I've to study man pages from linux, BSD...and Alpine seems to the last flavour. We never stop to learn here into the wild :)

Thanks for helping out. I'd like to publish the branch/image in the next week.

I hope it sounds all good to @simonbland too, even if it's not having a lot of time to follow the project in the last month :) <3

Cheers

**Comment by simonbland** [comment]
Hi @maiorano84 and @pioneerskies,

Sorry for the delay.

It sounds good to me, as soon as this version is published under the `alpine` tag. I can imagine it will have to be tested a lot before becoming the main version.

Now, I will have a little more time than in the past few months to look after the the existing `ubuntu` based `docker-wordmove` project, but still not enough to invest in the maintenance of this `alpine` version, as I have to admit I don't know this distribution at all.

@pioneerskies do you think it's mature enough to publish it and let the community test and improve it?

**Comment by alessandro-fazzi** [comment]
@maiorano84 `welaika/wordmove:alpine` is ready to be tested. Closing this issue and waiting for bugs ;)
